third homework partially done
Ilichev-vlad/Restaraunts pull request #3
Opened 2024-07-06 22:55 UTC by Ilichev-vlad

2024-07-06 22:57 UTC, Ilichev-vlad commented
Подскажите, как корректно переиспользовать счетчик, я возвращаю из него значение, но не меняю значение в самом счетчике, в консоли ошибка с рэндером вылезает
![image](https://github.com/Ilichev-vlad/Restaraunts/assets/60879718/87d57a52-fd9d-41bb-8b94-dff458a369e4)

2024-07-07 09:51 UTC, zubkov7 commented on src/components/counter/component.jsx
> +const useCount = (minValue, maxValue, onChange) => {
можно сделать параметры по умолчанию. В таких случаях удобно передавать объект в функцию, а внутри уже аргументы доставать из полей

{ minValue = 0, maxValue = 5, onChange }

2024-07-07 10:14 UTC, zubkov7 commented on src/components/review-form/component.jsx
> +                <Counter key={id} minValue={1} maxValue={5} onChange={(value) => {
тут проблема в том, что каунтер внутри себя меняет состояние и при этом меняется состояние формы. То есть каунтер при изменении формы в любом случае перерисуется

тут идея была в том, что использовать компонент Counter, который принимает increment, decrement и value. Формы уже сама передаст необходимые пропсы

2024-07-07 10:16 UTC, zubkov7 commented
получилось настроить prettier? вижу, что в некоторых местах разные отступы

плюс можно прогнать линтер pnpm run lint, он подсветит ошибки в коде при наличии

2024-07-07 10:16 UTC, zubkov7 requested changes

2024-07-07 10:16 UTC, zubkov7 commented on src/components/scroll-progress/component.jsx
> +    useEffect(() => {
забыли почистить eventListener, нужно использовать cleanup функцию

callback при этом можно вынести в отдельную переменную

2024-07-10 16:27 UTC, merged